// <auto-generated />
namespace Fractal.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MoveAuditstuffaroundforDCandDCF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveAuditstuffaroundforDCandDCF));
        
        string IMigrationMetadata.Id
        {
            get { return "201410062118108_Move Audit stuff around for DC and DCF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
